[package]
name = "test_parallel_1"
version = "0.1.0"
authors = ["rodolfodc <rodolfo.dalla.costa@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
