[package]
name = "calculadora"
version = "0.1.0"
authors = ["rodolfo dalla costa <rodolfo.dalla.costa@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
